name: Vulnerability Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get install -y curl jq
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Run Trivy Scan on Dependencies
        run: |
          mkdir -p reports
          trivy fs --scanners vuln,secret --format json --output reports/trivy-report.json .

      - name: Verify SARIF File
        run: ls -l reports/

      - name: Save SARIF as Artifact (For Private Repos)
        uses: actions/upload-artifact@v4  # Use v4 (latest stable version)
        with:
          name: sarif-reports
          path: reports/trivy-report.json

  semgrep-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep Scan (JSON Output)
        run: |
          mkdir -p reports
          semgrep scan --config=auto --json > reports/semgrep-report.json

      - name: Save Semgrep JSON Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: reports/semgrep-report.json